# using for dev
version: '3.8'
services:
    vetgo-redis:
        image: redis:alpine
        container_name: vetgo-redis
        expose:
            - 6379
        ports:
            - 6379:6379 # public port để test mutiple worker     
        restart: unless-stopped 
    vetgo-redis-commander: 
        container_name: vetgo-redis-commander
        image: rediscommander/redis-commander:latest
        environment:
          - REDIS_HOSTS=local:vetgo-redis:6379
        ports:
          - '8088:8081'
        depends_on:
          - vetgo-redis   
    vetgo-database:
        image: postgres:15.0
        container_name: vetgo-database
        ports:
            - "5434:5432"
        environment:
            - POSTGRES_DB=vetgo
            - POSTGRES_USER=vetgo
            - POSTGRES_PASSWORD=Thanh71311@
        networks:
            - vetgo-network
networks:
    vetgo-network:
# docker compose up -d
# docker compose up -d vetgo-database

#docker logs vogo-database -> xem log
#docker exec -it vogo-database bash -> cmd

# psql -U vetgo -w vetgo
# \dt -> xem table
# select * from "table";
# exit 
# xoa het docker 
# docker compose rm vetgo-database --stop --force --volumes
