version: '3'

services:
  nosqlclient:
    image: mongoclient/mongoclient
    ports:
      - "8081:8081"  # Chuyển tiếp cổng 8081 của máy host sang cổng 8081 của container
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://127.0.0.1:27017
      -
    volumes:
      - ./data:/data  # Mount thư mục dữ liệu từ máy host vào container
